//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Files = new HashSet<File>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public decimal Price { get; set; }
        public string Gender { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> SoldCount { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<File> Files { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
